### ISSUE TITLE
Update turn/move request validators

### ISSUE THREAD

**Issue by jordan-powers** [lost1227/marsbot-challenge-client#1]
At the moment, the only validation on turn/move steps is a minimum of 1.

Check with @terbos90803 if this validation is correct, and if there are any other validations that make sense.

**Comment by terbos90803** [comment]
I would expect a minimum of 0 with decimal values allowed for both move and rotate.
Given the size of the playing field, we should probably cap moves to 10 steps (maybe 15?).
We should definitely limit rotation to 4 steps or 360 degrees.
